export const BRANDS = ['Trek', 'Giant', 'Specialized', 'Hero', 'Hercules', 'Firefox', 'Montra', 'Cannondale', 'Scott', 'Merida', 'Marin', 'Polygon', 'Btwin', 'Cradiac', 'Leader', 'Java', 'OMO', 'Kross'];
export const CATEGORIES = ['MTB', 'Road', 'Hybrid', 'Gravel', 'BMX', 'City', 'Touring', 'Urban', 'Electric'];

export const CATEGORY_BIKE_IMAGES = {
  'MTB': [
    'https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=800&q=80',
    'https://images.unsplash.com/photo-1576435728678-68d0fbf94946?w=800&q=80',
    'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800&q=80',
    'https://images.unsplash.com/photo-1504198458649-3128b932f49e?w=800&q=80',
    'https://images.unsplash.com/photo-1452378174528-3090a4bba7b2?w=800&q=80',
  ],
  'Road': [
    'https://images.unsplash.com/photo-1559348349-86f1f65817fe?w=800&q=80',
    'https://images.unsplash.com/photo-1571333250630-f0230c320b6d?w=800&q=80',
    'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&q=80',
    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=800&q=80',
  ],
  'Hybrid': [
    'https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?w=800&q=80',
    'https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=800&q=80',
    'https://images.unsplash.com/photo-1511994298241-608e28f14fde?w=800&q=80',
    'https://images.unsplash.com/photo-1502744688674-c619d1586c9e?w=800&q=80',
    'https://images.unsplash.com/photo-1505705694340-019e1e335916?w=800&q=80',
  ],
  'Gravel': [
    'https://images.unsplash.com/photo-1593764592116-bfb2a97c642a?w=800&q=80',
    'https://images.unsplash.com/photo-1526401485004-46910ecc8e51?w=800&q=80',
    'https://images.unsplash.com/photo-1478407585014-54b2aba46565?w=800&q=80',
    'https://images.unsplash.com/photo-1572629781832-c8d57d38f81e?w=800&q=80',
    'https://images.unsplash.com/photo-1533107862482-0e6974b06ec4?w=800&q=80',
  ],
  'City': [
    'https://images.unsplash.com/photo-1502744688674-c619d1586c9e?w=800&q=80',
    'https://images.unsplash.com/photo-1505705694340-019e1e335916?w=800&q=80',
    'https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=800&q=80',
    'https://images.unsplash.com/photo-1526401363977-13b198f25f7d?w=800&q=80',
    'https://images.unsplash.com/photo-1470114716159-e389f8712fda?w=800&q=80',
  ],
  'Electric': [
    'https://images.unsplash.com/photo-1572629781832-c8d57d38f81e?w=800&q=80',
    'https://images.unsplash.com/photo-1549880338-65ddcdfd017b?w=800&q=80',
    'https://images.unsplash.com/photo-1593764592116-bfb2a97c642a?w=800&q=80',
    'https://images.unsplash.com/photo-1526401363977-13b198f25f7d?w=800&q=80',
    'https://images.unsplash.com/photo-1478407585014-54b2aba46565?w=800&q=80',
  ],
}

export const CYCLE_IMAGES = {

  // ═══════════════════════════════
  // TREK — Official Trek CDN Images
  // ═══════════════════════════════
  'trek-marlin-4': 'https://trek.scene7.com/is/image/TrekBicycleProducts/Marlin4_23_34035_A_Primary?wid=800&hei=600&fmt=png-alpha',
  'trek-marlin-5': 'https://trek.scene7.com/is/image/TrekBicycleProducts/Marlin5_23_34036_A_Primary?wid=800&hei=600&fmt=png-alpha',
  'trek-marlin-6': 'https://trek.scene7.com/is/image/TrekBicycleProducts/Marlin6_23_34037_A_Primary?wid=800&hei=600&fmt=png-alpha',
  'trek-marlin-7': 'https://trek.scene7.com/is/image/TrekBicycleProducts/Marlin7_23_34038_A_Primary?wid=800&hei=600&fmt=png-alpha',
  'trek-marlin-8': 'https://trek.scene7.com/is/image/TrekBicycleProducts/Marlin8_23_34039_A_Primary?wid=800&hei=600&fmt=png-alpha',
  'trek-fx-1': 'https://trek.scene7.com/is/image/TrekBicycleProducts/FX1_23_34040_A_Primary?wid=800&hei=600&fmt=png-alpha',
  'trek-fx-2': 'https://trek.scene7.com/is/image/TrekBicycleProducts/FX2_23_34041_A_Primary?wid=800&hei=600&fmt=png-alpha',
  'trek-fx-3': 'https://trek.scene7.com/is/image/TrekBicycleProducts/FX3_23_34042_A_Primary?wid=800&hei=600&fmt=png-alpha',
  'trek-verve-1': 'https://trek.scene7.com/is/image/TrekBicycleProducts/Verve1_23_A_Primary?wid=800&hei=600&fmt=png-alpha',
  'trek-verve-2': 'https://trek.scene7.com/is/image/TrekBicycleProducts/Verve2_23_A_Primary?wid=800&hei=600&fmt=png-alpha',
  'trek-domane-al-2': 'https://trek.scene7.com/is/image/TrekBicycleProducts/DomaneAL2_23_A_Primary?wid=800&hei=600&fmt=png-alpha',
  'trek-domane-al-3': 'https://trek.scene7.com/is/image/TrekBicycleProducts/DomaneAL3_23_A_Primary?wid=800&hei=600&fmt=png-alpha',
  'trek-dual-sport-1': 'https://trek.scene7.com/is/image/TrekBicycleProducts/DualSport1_23_A_Primary?wid=800&hei=600&fmt=png-alpha',
  'trek-dual-sport-2': 'https://trek.scene7.com/is/image/TrekBicycleProducts/DualSport2_23_A_Primary?wid=800&hei=600&fmt=png-alpha',
  'trek-dual-sport-3': 'https://trek.scene7.com/is/image/TrekBicycleProducts/DualSport3_23_A_Primary?wid=800&hei=600&fmt=png-alpha',
  'trek-x-caliber-7': 'https://trek.scene7.com/is/image/TrekBicycleProducts/XCaliber7_23_A_Primary?wid=800&hei=600&fmt=png-alpha',
  'trek-x-caliber-8': 'https://trek.scene7.com/is/image/TrekBicycleProducts/XCaliber8_23_A_Primary?wid=800&hei=600&fmt=png-alpha',
  'trek-roscoe-7': 'https://trek.scene7.com/is/image/TrekBicycleProducts/Roscoe7_23_A_Primary?wid=800&hei=600&fmt=png-alpha',
  'trek-roscoe-8': 'https://trek.scene7.com/is/image/TrekBicycleProducts/Roscoe8_23_A_Primary?wid=800&hei=600&fmt=png-alpha',
  'trek-slash-9-8': 'https://trek.scene7.com/is/image/TrekBicycleProducts/Slash98_23_A_Primary?wid=800&hei=600&fmt=png-alpha',

  // ═══════════════════════════════
  // GIANT — Official Giant Images
  // ═══════════════════════════════
  'giant-talon-1': 'https://www.giant-bicycles.com/medias/sys_master/bikes/bikes/h67/h23/8814227963934/TALON-1-GE-A-2023.png',
  'giant-talon-2': 'https://www.giant-bicycles.com/medias/sys_master/bikes/bikes/h67/h23/8814227963934/TALON-2-GE-A-2023.png',
  'giant-talon-3': 'https://www.giant-bicycles.com/medias/sys_master/bikes/bikes/h67/h23/8814227963934/TALON-3-GE-A-2023.png',
  'giant-atx': 'https://www.giant-bicycles.com/medias/sys_master/bikes/bikes/ATX-GE-A-2023.png',
  'giant-atx-1': 'https://www.giant-bicycles.com/medias/sys_master/bikes/bikes/ATX-1-GE-A-2023.png',
  'giant-atx-2': 'https://www.giant-bicycles.com/medias/sys_master/bikes/bikes/ATX-2-GE-A-2023.png',
  'giant-escape-2': 'https://www.giant-bicycles.com/medias/sys_master/bikes/bikes/ESCAPE-2-GE-A-2023.png',
  'giant-escape-3': 'https://www.giant-bicycles.com/medias/sys_master/bikes/bikes/ESCAPE-3-GE-A-2023.png',
  'giant-contend-3': 'https://www.giant-bicycles.com/medias/sys_master/bikes/bikes/CONTEND-3-GE-A-2023.png',
  'giant-contend-ar': 'https://www.giant-bicycles.com/medias/sys_master/bikes/bikes/CONTEND-AR-GE-A-2023.png',
  'giant-revolt-2': 'https://www.giant-bicycles.com/medias/sys_master/bikes/bikes/REVOLT-2-GE-A-2023.png',
  'giant-roam-2': 'https://www.giant-bicycles.com/medias/sys_master/bikes/bikes/ROAM-2-GE-A-2023.png',
  'giant-roam-3': 'https://www.giant-bicycles.com/medias/sys_master/bikes/bikes/ROAM-3-GE-A-2023.png',
  'giant-fathom-1': 'https://www.giant-bicycles.com/medias/sys_master/bikes/bikes/FATHOM-1-GE-A-2023.png',
  'giant-fathom-2': 'https://www.giant-bicycles.com/medias/sys_master/bikes/bikes/FATHOM-2-GE-A-2023.png',
  'giant-trance-x': 'https://www.giant-bicycles.com/medias/sys_master/bikes/bikes/TRANCE-X-GE-A-2023.png',
  'giant-stance-2': 'https://www.giant-bicycles.com/medias/sys_master/bikes/bikes/STANCE-2-GE-A-2023.png',
  'giant-propel-advanced': 'https://www.giant-bicycles.com/medias/sys_master/bikes/bikes/PROPEL-ADVANCED-GE-A-2023.png',
  'giant-defy-advanced': 'https://www.giant-bicycles.com/medias/sys_master/bikes/bikes/DEFY-ADVANCED-GE-A-2023.png',
  'giant-fastroad-sl': 'https://www.giant-bicycles.com/medias/sys_master/bikes/bikes/FASTROAD-SL-GE-A-2023.png',

  // ═══════════════════════════════
  // SPECIALIZED
  // ═══════════════════════════════
  'specialized-rockhopper': 'https://assets.specialized.com/i/specialized/91823-00_ROCKHOPPER-BASE-SATIN-GLOSS-TARMAC-BLACK_HERO?bg=rgb(255,255,255)&w=800&h=600',
  'specialized-rockhopper-comp': 'https://assets.specialized.com/i/specialized/91824-00_ROCKHOPPER-COMP-SATIN-SMOKE_HERO?bg=rgb(255,255,255)&w=800&h=600',
  'specialized-rockhopper-elite': 'https://assets.specialized.com/i/specialized/91825-00_ROCKHOPPER-ELITE_HERO?bg=rgb(255,255,255)&w=800&h=600',
  'specialized-hardrock': 'https://assets.specialized.com/i/specialized/91820-00_HARDROCK-SPORT_HERO?bg=rgb(255,255,255)&w=800&h=600',
  'specialized-pitch': 'https://assets.specialized.com/i/specialized/91819-00_PITCH_HERO?bg=rgb(255,255,255)&w=800&h=600',
  'specialized-sirrus-2': 'https://assets.specialized.com/i/specialized/90321-00_SIRRUS-2_HERO?bg=rgb(255,255,255)&w=800&h=600',
  'specialized-sirrus-x': 'https://assets.specialized.com/i/specialized/90322-00_SIRRUS-X_HERO?bg=rgb(255,255,255)&w=800&h=600',
  'specialized-allez': 'https://assets.specialized.com/i/specialized/90100-00_ALLEZ_HERO?bg=rgb(255,255,255)&w=800&h=600',
  'specialized-allez-elite': 'https://assets.specialized.com/i/specialized/90101-00_ALLEZ-ELITE_HERO?bg=rgb(255,255,255)&w=800&h=600',
  'specialized-diverge': 'https://assets.specialized.com/i/specialized/90400-00_DIVERGE_HERO?bg=rgb(255,255,255)&w=800&h=600',
  'specialized-roubaix': 'https://assets.specialized.com/i/specialized/90200-00_ROUBAIX_HERO?bg=rgb(255,255,255)&w=800&h=600',
  'specialized-stumpjumper': 'https://assets.specialized.com/i/specialized/93020-00_STUMPJUMPER_HERO?bg=rgb(255,255,255)&w=800&h=600',
  'specialized-turbo-vado': 'https://assets.specialized.com/i/specialized/96420-00_TURBO-VADO_HERO?bg=rgb(255,255,255)&w=800&h=600',
  'specialized-turbo-como': 'https://assets.specialized.com/i/specialized/96421-00_TURBO-COMO_HERO?bg=rgb(255,255,255)&w=800&h=600',
  'specialized-epic-hardtail': 'https://assets.specialized.com/i/specialized/93323-00_EPIC-HARDTAIL_HERO?bg=rgb(255,255,255)&w=800&h=600',
  'specialized-epic-evo': 'https://assets.specialized.com/i/specialized/93324-00_EPIC-EVO_HERO?bg=rgb(255,255,255)&w=800&h=600',
  'specialized-fuse': 'https://assets.specialized.com/i/specialized/93120-00_FUSE_HERO?bg=rgb(255,255,255)&w=800&h=600',
  'specialized-enduro': 'https://assets.specialized.com/i/specialized/93420-00_ENDURO_HERO?bg=rgb(255,255,255)&w=800&h=600',
  'specialized-demo': 'https://assets.specialized.com/i/specialized/93520-00_DEMO_HERO?bg=rgb(255,255,255)&w=800&h=600',
  'specialized-tarmac': 'https://assets.specialized.com/i/specialized/90300-00_TARMAC_HERO?bg=rgb(255,255,255)&w=800&h=600',

  // ═══════════════════════════════
  // INDIAN BRANDS — Use verified
  // cycling stock photos that show
  // actual bikes similar to these
  // ═══════════════════════════════
  'hero-sprint-pro': 'https://www.herocycles.com/dw/image/v2/BCWL_PRD/on/demandware.static/-/Sites-HeroCycles-Library/default/sprint-pro.jpg?sw=800',
  'hero-sprint-compass': 'https://www.herocycles.com/dw/image/v2/BCWL_PRD/on/demandware.static/-/Sites-HeroCycles-Library/default/sprint-compass.jpg?sw=800',
  'hero-octane-bonito': 'https://www.herocycles.com/dw/image/v2/BCWL_PRD/on/demandware.static/-/Sites-HeroCycles-Library/default/octane-bonito.jpg?sw=800',
  'hero-octane-salamander': 'https://www.herocycles.com/dw/image/v2/BCWL_PRD/on/demandware.static/-/Sites-HeroCycles-Library/default/octane-salamander.jpg?sw=800',
  'hero-octane-parkour': 'https://www.herocycles.com/dw/image/v2/BCWL_PRD/on/demandware.static/-/Sites-HeroCycles-Library/default/octane-parkour.jpg?sw=800',

  // HERCULES
  'hercules-roadeo-a50': 'https://www.hercules-cycle.com/pub/media/catalog/product/r/o/roadeo-a50.jpg',
  'hercules-roadeo-a75': 'https://www.hercules-cycle.com/pub/media/catalog/product/r/o/roadeo-a75.jpg',
  'hercules-roadeo-turnkey': 'https://www.hercules-cycle.com/pub/media/catalog/product/r/o/roadeo-turnkey.jpg',
  'hercules-top-gear': 'https://www.hercules-cycle.com/pub/media/catalog/product/t/o/top-gear.jpg',
  'hercules-street-rider': 'https://www.hercules-cycle.com/pub/media/catalog/product/s/t/street-rider.jpg',

  // FIREFOX
  'firefox-mountana-29': 'https://www.firefoxbikes.com/pub/media/catalog/product/m/o/mountana-29.jpg',
  'firefox-road-runner': 'https://www.firefoxbikes.com/pub/media/catalog/product/r/o/road-runner.jpg',
  'firefox-bad-attitude-7': 'https://www.firefoxbikes.com/pub/media/catalog/product/b/a/bad-attitude-7.jpg',
  'firefox-voya': 'https://www.firefoxbikes.com/pub/media/catalog/product/v/o/voya.jpg',
  'firefox-rapide': 'https://www.firefoxbikes.com/pub/media/catalog/product/r/a/rapide.jpg',

  // MONTRA
  'montra-madrock': 'https://www.montra.in/pub/media/catalog/product/m/a/madrock.jpg',
  'montra-downtown': 'https://www.montra.in/pub/media/catalog/product/d/o/downtown.jpg',
  'montra-blues': 'https://www.montra.in/pub/media/catalog/product/b/l/blues.jpg',
  'montra-chord': 'https://www.montra.in/pub/media/catalog/product/c/h/chord.jpg',
  'montra-trance': 'https://www.montra.in/pub/media/catalog/product/t/r/trance.jpg',

  // ═══════════════════════════════
  // CANNONDALE
  // ═══════════════════════════════
  'cannondale-trail-5': 'https://www.cannondale.com/en-us/bikes/mountain/trail-bikes/trail/trail-5?color=C26851U10OS',
  'cannondale-trail-6': 'https://assets.cannondale.com/is/image/cannondale/C26851U10OS_Trail6_Hero?wid=800&hei=600',
  'cannondale-trail-7': 'https://assets.cannondale.com/is/image/cannondale/C26852U10OS_Trail7_Hero?wid=800&hei=600',
  'cannondale-quick-3': 'https://assets.cannondale.com/is/image/cannondale/C62351U10OS_Quick3_Hero?wid=800&hei=600',
  'cannondale-quick-cx-4': 'https://assets.cannondale.com/is/image/cannondale/C62451U10OS_QuickCX4_Hero?wid=800&hei=600',

  // SCOTT
  'scott-aspect-940': 'https://www.scott-sports.com/on/demandware.static/Sites-SCOTT-SportsSite/Libraries/default/aspect-940.jpg',
  'scott-aspect-950': 'https://www.scott-sports.com/on/demandware.static/Sites-SCOTT-SportsSite/Libraries/default/aspect-950.jpg',
  'scott-scale-970': 'https://www.scott-sports.com/on/demandware.static/Sites-SCOTT-SportsSite/Libraries/default/scale-970.jpg',
  'scott-contessa-active': 'https://www.scott-sports.com/on/demandware.static/Sites-SCOTT-SportsSite/Libraries/default/contessa-active.jpg',

  // MERIDA
  'merida-big-nine-100': 'https://www.merida-bikes.com/fileadmin/ProductImages/2023/big-nine-100.jpg',
  'merida-big-nine-200': 'https://www.merida-bikes.com/fileadmin/ProductImages/2023/big-nine-200.jpg',
  'merida-big-seven-100': 'https://www.merida-bikes.com/fileadmin/ProductImages/2023/big-seven-100.jpg',
  'merida-scultura-200': 'https://www.merida-bikes.com/fileadmin/ProductImages/2023/scultura-200.jpg',
  'merida-crossway-20': 'https://www.merida-bikes.com/fileadmin/ProductImages/2023/crossway-20.jpg',

  // MARIN
  'marin-fairfax-1': 'https://www.marinbikes.com/medias/sys_master/bikes/fairfax-1-2023.jpg',
  'marin-fairfax-2': 'https://www.marinbikes.com/medias/sys_master/bikes/fairfax-2-2023.jpg',
  'marin-bobcat-trail': 'https://www.marinbikes.com/medias/sys_master/bikes/bobcat-trail-2023.jpg',
  'marin-gestalt': 'https://www.marinbikes.com/medias/sys_master/bikes/gestalt-2023.jpg',
  'marin-rift-zone': 'https://www.marinbikes.com/medias/sys_master/bikes/rift-zone-2023.jpg',
  'marin-dsx': 'https://www.marinbikes.com/medias/sys_master/bikes/dsx-2023.jpg',

  // ═══════════════════════════════
  // OTHERS
  // ═══════════════════════════════
  'polygon-path-2': 'https://www.polygonbikes.com/wp-content/uploads/2023/path-2.jpg',
  'polygon-strattos-s2': 'https://www.polygonbikes.com/wp-content/uploads/2023/strattos-s2.jpg',
  'polygon-cascade-3': 'https://www.polygonbikes.com/wp-content/uploads/2023/cascade-3.jpg',
  'polygon-xtrada-6': 'https://www.polygonbikes.com/wp-content/uploads/2023/xtrada-6.jpg',
  'polygon-heist-x2': 'https://www.polygonbikes.com/wp-content/uploads/2023/heist-x2.jpg',
  'btwin-rockrider-st100': 'https://contents.mediadecathlon.com/p1877145/rockrider-st100.jpg',
  'btwin-rockrider-st120': 'https://contents.mediadecathlon.com/p1877146/rockrider-st120.jpg',
  'btwin-rockrider-st520': 'https://contents.mediadecathlon.com/p1877147/rockrider-st520.jpg',
  'btwin-riverside-120': 'https://contents.mediadecathlon.com/p1877148/riverside-120.jpg',
  'btwin-riverside-500': 'https://contents.mediadecathlon.com/p1877149/riverside-500.jpg',
  'cradiac-gunner-pro': 'https://www.cradiac.com/images/gunner-pro.jpg',
  'cradiac-squad': 'https://www.cradiac.com/images/squad.jpg',
  'cradiac-alpha-pro': 'https://www.cradiac.com/images/alpha-pro.jpg',
  'leader-beast-26t': 'https://www.leadercycles.in/images/beast-26t.jpg',
  'leader-scout': 'https://www.leadercycles.in/images/scout.jpg',
  'java-fuoco': 'https://www.javabikes.com/images/fuoco.jpg',
  'omo-hybrid-700c': 'https://www.omobikes.com/images/hybrid-700c.jpg',
  'kross-maximus': 'https://www.kross.eu/images/maximus.jpg',
  'kross-xceed': 'https://www.kross.eu/images/xceed.jpg',
  'kross-viper': 'https://www.kross.eu/images/viper.jpg',
}

export const MOCK_CYCLES = [
  {
    id: 'trek-marlin-4',
    name: 'Marlin 4',
    brand: 'Trek',
    fullName: 'Trek Marlin 4',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹32,000',
    price_usd: '$385',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/trek-marlin-4.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'trek-marlin-5',
    name: 'Marlin 5',
    brand: 'Trek',
    fullName: 'Trek Marlin 5',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹38,000',
    price_usd: '$457',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/trek-marlin-5.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'trek-marlin-6',
    name: 'Marlin 6',
    brand: 'Trek',
    fullName: 'Trek Marlin 6',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹48,000',
    price_usd: '$578',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/trek-marlin-6.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'trek-marlin-7',
    name: 'Marlin 7',
    brand: 'Trek',
    fullName: 'Trek Marlin 7',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹62,000',
    price_usd: '$746',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/trek-marlin-7.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'trek-marlin-8',
    name: 'Marlin 8',
    brand: 'Trek',
    fullName: 'Trek Marlin 8',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹75,000',
    price_usd: '$903',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/trek-marlin-8.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'trek-fx-1',
    name: 'FX 1',
    brand: 'Trek',
    fullName: 'Trek FX 1',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹38,000',
    price_usd: '$457',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/trek-fx-1.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'trek-fx-2',
    name: 'FX 2',
    brand: 'Trek',
    fullName: 'Trek FX 2',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹52,000',
    price_usd: '$626',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/trek-fx-2.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'trek-fx-3',
    name: 'FX 3',
    brand: 'Trek',
    fullName: 'Trek FX 3',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹68,000',
    price_usd: '$819',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/trek-fx-3.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'trek-verve-1',
    name: 'Verve 1',
    brand: 'Trek',
    fullName: 'Trek Verve 1',
    category: 'City',
    type: 'City Bike',
    price_inr: '₹32,000',
    price_usd: '$385',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/trek-verve-1.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'trek-verve-2',
    name: 'Verve 2',
    brand: 'Trek',
    fullName: 'Trek Verve 2',
    category: 'City',
    type: 'City Bike',
    price_inr: '₹42,000',
    price_usd: '$506',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/trek-verve-2.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'trek-domane-al-2',
    name: 'Domane AL 2',
    brand: 'Trek',
    fullName: 'Trek Domane AL 2',
    category: 'Road',
    type: 'Road Bike',
    price_inr: '₹72,000',
    price_usd: '$867',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/trek-domane-al-2.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'trek-domane-al-3',
    name: 'Domane AL 3',
    brand: 'Trek',
    fullName: 'Trek Domane AL 3',
    category: 'Road',
    type: 'Road Bike',
    price_inr: '₹92,000',
    price_usd: '$1108',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/trek-domane-al-3.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'trek-dual-sport-1',
    name: 'Dual Sport 1',
    brand: 'Trek',
    fullName: 'Trek Dual Sport 1',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹35,000',
    price_usd: '$421',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/trek-dual-sport-1.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'trek-dual-sport-2',
    name: 'Dual Sport 2',
    brand: 'Trek',
    fullName: 'Trek Dual Sport 2',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹45,000',
    price_usd: '$542',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/trek-dual-sport-2.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'trek-dual-sport-3',
    name: 'Dual Sport 3',
    brand: 'Trek',
    fullName: 'Trek Dual Sport 3',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹58,000',
    price_usd: '$698',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/trek-dual-sport-3.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'trek-x-caliber-7',
    name: 'X-Caliber 7',
    brand: 'Trek',
    fullName: 'Trek X-Caliber 7',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹82,000',
    price_usd: '$987',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/trek-x-caliber-7.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'trek-x-caliber-8',
    name: 'X-Caliber 8',
    brand: 'Trek',
    fullName: 'Trek X-Caliber 8',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹1,05,000',
    price_usd: '$1265',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/trek-x-caliber-8.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'trek-roscoe-7',
    name: 'Roscoe 7',
    brand: 'Trek',
    fullName: 'Trek Roscoe 7',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹92,000',
    price_usd: '$1108',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/trek-roscoe-7.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'trek-roscoe-8',
    name: 'Roscoe 8',
    brand: 'Trek',
    fullName: 'Trek Roscoe 8',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹1,15,000',
    price_usd: '$1385',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/trek-roscoe-8.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'trek-slash-98',
    name: 'Slash 9.8',
    brand: 'Trek',
    fullName: 'Trek Slash 9.8',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹3,50,000',
    price_usd: '$4216',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/trek-slash-98.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'giant-talon-1',
    name: 'Talon 1',
    brand: 'Giant',
    fullName: 'Giant Talon 1',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹42,000',
    price_usd: '$506',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/giant-talon-1.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'giant-talon-2',
    name: 'Talon 2',
    brand: 'Giant',
    fullName: 'Giant Talon 2',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹35,000',
    price_usd: '$421',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/giant-talon-2.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'giant-talon-3',
    name: 'Talon 3',
    brand: 'Giant',
    fullName: 'Giant Talon 3',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹28,000',
    price_usd: '$337',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/giant-talon-3.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'giant-atx',
    name: 'ATX',
    brand: 'Giant',
    fullName: 'Giant ATX',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹22,000',
    price_usd: '$265',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/giant-atx.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'giant-atx-1',
    name: 'ATX 1',
    brand: 'Giant',
    fullName: 'Giant ATX 1',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹25,000',
    price_usd: '$301',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/giant-atx-1.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'giant-atx-2',
    name: 'ATX 2',
    brand: 'Giant',
    fullName: 'Giant ATX 2',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹28,000',
    price_usd: '$337',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/giant-atx-2.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'giant-escape-2',
    name: 'Escape 2',
    brand: 'Giant',
    fullName: 'Giant Escape 2',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹38,000',
    price_usd: '$457',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/giant-escape-2.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'giant-escape-3',
    name: 'Escape 3',
    brand: 'Giant',
    fullName: 'Giant Escape 3',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹32,000',
    price_usd: '$385',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/giant-escape-3.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'giant-contend-3',
    name: 'Contend 3',
    brand: 'Giant',
    fullName: 'Giant Contend 3',
    category: 'Road',
    type: 'Road Bike',
    price_inr: '₹52,000',
    price_usd: '$626',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/giant-contend-3.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'giant-contend-ar',
    name: 'Contend AR',
    brand: 'Giant',
    fullName: 'Giant Contend AR',
    category: 'Road',
    type: 'Road Bike',
    price_inr: '₹68,000',
    price_usd: '$819',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/giant-contend-ar.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'giant-revolt-2',
    name: 'Revolt 2',
    brand: 'Giant',
    fullName: 'Giant Revolt 2',
    category: 'Gravel',
    type: 'Gravel Bike',
    price_inr: '₹58,000',
    price_usd: '$698',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/giant-revolt-2.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'giant-roam-2',
    name: 'Roam 2',
    brand: 'Giant',
    fullName: 'Giant Roam 2',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹35,000',
    price_usd: '$421',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/giant-roam-2.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'giant-roam-3',
    name: 'Roam 3',
    brand: 'Giant',
    fullName: 'Giant Roam 3',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹28,000',
    price_usd: '$337',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/giant-roam-3.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'giant-fathom-1',
    name: 'Fathom 1',
    brand: 'Giant',
    fullName: 'Giant Fathom 1',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹82,000',
    price_usd: '$987',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/giant-fathom-1.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'giant-fathom-2',
    name: 'Fathom 2',
    brand: 'Giant',
    fullName: 'Giant Fathom 2',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹65,000',
    price_usd: '$783',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/giant-fathom-2.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'giant-trance-x',
    name: 'Trance X',
    brand: 'Giant',
    fullName: 'Giant Trance X',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹1,85,000',
    price_usd: '$2228',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/giant-trance-x.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'giant-stance-2',
    name: 'Stance 2',
    brand: 'Giant',
    fullName: 'Giant Stance 2',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹72,000',
    price_usd: '$867',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/giant-stance-2.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'giant-propel-advanced',
    name: 'Propel Advanced',
    brand: 'Giant',
    fullName: 'Giant Propel Advanced',
    category: 'Road',
    type: 'Road Bike',
    price_inr: '₹2,20,000',
    price_usd: '$2650',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/giant-propel-advanced.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'giant-defy-advanced',
    name: 'Defy Advanced',
    brand: 'Giant',
    fullName: 'Giant Defy Advanced',
    category: 'Road',
    type: 'Road Bike',
    price_inr: '₹1,65,000',
    price_usd: '$1987',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/giant-defy-advanced.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'giant-fastroad-sl',
    name: 'FastRoad SL',
    brand: 'Giant',
    fullName: 'Giant FastRoad SL',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹85,000',
    price_usd: '$1024',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/giant-fastroad-sl.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'specialized-rockhopper',
    name: 'Rockhopper',
    brand: 'Specialized',
    fullName: 'Specialized Rockhopper',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹38,000',
    price_usd: '$457',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/specialized-rockhopper.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'specialized-rockhopper-comp',
    name: 'Rockhopper Comp',
    brand: 'Specialized',
    fullName: 'Specialized Rockhopper Comp',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹52,000',
    price_usd: '$626',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/specialized-rockhopper-comp.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'specialized-rockhopper-elite',
    name: 'Rockhopper Elite',
    brand: 'Specialized',
    fullName: 'Specialized Rockhopper Elite',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹68,000',
    price_usd: '$819',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/specialized-rockhopper-elite.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'specialized-hardrock',
    name: 'Hardrock',
    brand: 'Specialized',
    fullName: 'Specialized Hardrock',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹28,000',
    price_usd: '$337',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/specialized-hardrock.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'specialized-pitch',
    name: 'Pitch',
    brand: 'Specialized',
    fullName: 'Specialized Pitch',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹22,000',
    price_usd: '$265',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/specialized-pitch.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'specialized-sirrus-20',
    name: 'Sirrus 2.0',
    brand: 'Specialized',
    fullName: 'Specialized Sirrus 2.0',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹52,000',
    price_usd: '$626',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/specialized-sirrus-20.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'specialized-sirrus-x',
    name: 'Sirrus X',
    brand: 'Specialized',
    fullName: 'Specialized Sirrus X',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹68,000',
    price_usd: '$819',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/specialized-sirrus-x.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'specialized-allez',
    name: 'Allez',
    brand: 'Specialized',
    fullName: 'Specialized Allez',
    category: 'Road',
    type: 'Road Bike',
    price_inr: '₹72,000',
    price_usd: '$867',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/specialized-allez.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'specialized-allez-elite',
    name: 'Allez Elite',
    brand: 'Specialized',
    fullName: 'Specialized Allez Elite',
    category: 'Road',
    type: 'Road Bike',
    price_inr: '₹95,000',
    price_usd: '$1144',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/specialized-allez-elite.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'specialized-diverge',
    name: 'Diverge',
    brand: 'Specialized',
    fullName: 'Specialized Diverge',
    category: 'Gravel',
    type: 'Gravel Bike',
    price_inr: '₹1,15,000',
    price_usd: '$1385',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/specialized-diverge.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'specialized-roubaix',
    name: 'Roubaix',
    brand: 'Specialized',
    fullName: 'Specialized Roubaix',
    category: 'Road',
    type: 'Road Bike',
    price_inr: '₹1,45,000',
    price_usd: '$1746',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/specialized-roubaix.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'specialized-stumpjumper',
    name: 'Stumpjumper',
    brand: 'Specialized',
    fullName: 'Specialized Stumpjumper',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹1,85,000',
    price_usd: '$2228',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/specialized-stumpjumper.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'specialized-turbo-vado',
    name: 'Turbo Vado',
    brand: 'Specialized',
    fullName: 'Specialized Turbo Vado',
    category: 'Electric',
    type: 'Electric Bike',
    price_inr: '₹2,50,000',
    price_usd: '$3012',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/specialized-turbo-vado.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'specialized-turbo-como',
    name: 'Turbo Como',
    brand: 'Specialized',
    fullName: 'Specialized Turbo Como',
    category: 'Electric',
    type: 'Electric Bike',
    price_inr: '₹2,20,000',
    price_usd: '$2650',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/specialized-turbo-como.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'specialized-epic-hardtail',
    name: 'Epic Hardtail',
    brand: 'Specialized',
    fullName: 'Specialized Epic Hardtail',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹1,25,000',
    price_usd: '$1506',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/specialized-epic-hardtail.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'specialized-epic-evo',
    name: 'Epic Evo',
    brand: 'Specialized',
    fullName: 'Specialized Epic Evo',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹2,80,000',
    price_usd: '$3373',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/specialized-epic-evo.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'specialized-fuse',
    name: 'Fuse',
    brand: 'Specialized',
    fullName: 'Specialized Fuse',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹1,15,000',
    price_usd: '$1385',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/specialized-fuse.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'specialized-enduro',
    name: 'Enduro',
    brand: 'Specialized',
    fullName: 'Specialized Enduro',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹2,45,000',
    price_usd: '$2951',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/specialized-enduro.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'specialized-demo',
    name: 'Demo',
    brand: 'Specialized',
    fullName: 'Specialized Demo',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹3,20,000',
    price_usd: '$3855',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/specialized-demo.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'specialized-tarmac',
    name: 'Tarmac',
    brand: 'Specialized',
    fullName: 'Specialized Tarmac',
    category: 'Road',
    type: 'Road Bike',
    price_inr: '₹2,15,000',
    price_usd: '$2590',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/specialized-tarmac.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'hero-sprint-pro',
    name: 'Sprint Pro',
    brand: 'Hero',
    fullName: 'Hero Sprint Pro',
    category: 'Road',
    type: 'Road Bike',
    price_inr: '₹18,000',
    price_usd: '$216',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/hero-sprint-pro.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'hero-sprint-compass',
    name: 'Sprint Compass',
    brand: 'Hero',
    fullName: 'Hero Sprint Compass',
    category: 'Road',
    type: 'Road Bike',
    price_inr: '₹14,000',
    price_usd: '$168',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/hero-sprint-compass.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'hero-octane-bonito',
    name: 'Octane Bonito',
    brand: 'Hero',
    fullName: 'Hero Octane Bonito',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹16,000',
    price_usd: '$192',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/hero-octane-bonito.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'hero-octane-salamander',
    name: 'Octane Salamander',
    brand: 'Hero',
    fullName: 'Hero Octane Salamander',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹18,000',
    price_usd: '$216',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/hero-octane-salamander.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'hero-octane-parkour',
    name: 'Octane Parkour',
    brand: 'Hero',
    fullName: 'Hero Octane Parkour',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹22,000',
    price_usd: '$265',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/hero-octane-parkour.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'hercules-roadeo-a50',
    name: 'Roadeo A50',
    brand: 'Hercules',
    fullName: 'Hercules Roadeo A50',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹8,500',
    price_usd: '$102',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/hercules-roadeo-a50.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'hercules-roadeo-a75',
    name: 'Roadeo A75',
    brand: 'Hercules',
    fullName: 'Hercules Roadeo A75',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹10,500',
    price_usd: '$126',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/hercules-roadeo-a75.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'hercules-roadeo-turnkey',
    name: 'Roadeo Turnkey',
    brand: 'Hercules',
    fullName: 'Hercules Roadeo Turnkey',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹12,000',
    price_usd: '$144',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/hercules-roadeo-turnkey.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'hercules-top-gear',
    name: 'Top Gear',
    brand: 'Hercules',
    fullName: 'Hercules Top Gear',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹9,500',
    price_usd: '$114',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/hercules-top-gear.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'hercules-street-rider',
    name: 'Street Rider',
    brand: 'Hercules',
    fullName: 'Hercules Street Rider',
    category: 'City',
    type: 'City Bike',
    price_inr: '₹7,500',
    price_usd: '$90',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/hercules-street-rider.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'firefox-mountana-29',
    name: 'Mountana 29',
    brand: 'Firefox',
    fullName: 'Firefox Mountana 29',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹22,000',
    price_usd: '$265',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/firefox-mountana-29.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'firefox-road-runner',
    name: 'Road Runner',
    brand: 'Firefox',
    fullName: 'Firefox Road Runner',
    category: 'Road',
    type: 'Road Bike',
    price_inr: '₹18,000',
    price_usd: '$216',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/firefox-road-runner.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'firefox-bad-attitude-7',
    name: 'Bad Attitude 7',
    brand: 'Firefox',
    fullName: 'Firefox Bad Attitude 7',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹28,000',
    price_usd: '$337',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/firefox-bad-attitude-7.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'firefox-voya',
    name: 'Voya',
    brand: 'Firefox',
    fullName: 'Firefox Voya',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹16,000',
    price_usd: '$192',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/firefox-voya.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'firefox-rapide',
    name: 'Rapide',
    brand: 'Firefox',
    fullName: 'Firefox Rapide',
    category: 'Road',
    type: 'Road Bike',
    price_inr: '₹24,000',
    price_usd: '$289',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/firefox-rapide.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'montra-madrock',
    name: 'Madrock',
    brand: 'Montra',
    fullName: 'Montra Madrock',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹18,000',
    price_usd: '$216',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/montra-madrock.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'montra-downtown',
    name: 'Downtown',
    brand: 'Montra',
    fullName: 'Montra Downtown',
    category: 'City',
    type: 'City Bike',
    price_inr: '₹14,000',
    price_usd: '$168',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/montra-downtown.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'montra-blues',
    name: 'Blues',
    brand: 'Montra',
    fullName: 'Montra Blues',
    category: 'Road',
    type: 'Road Bike',
    price_inr: '₹22,000',
    price_usd: '$265',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/montra-blues.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'montra-chord',
    name: 'Chord',
    brand: 'Montra',
    fullName: 'Montra Chord',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹16,000',
    price_usd: '$192',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/montra-chord.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'montra-trance',
    name: 'Trance',
    brand: 'Montra',
    fullName: 'Montra Trance',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹24,000',
    price_usd: '$289',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/montra-trance.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'cannondale-trail-5',
    name: 'Trail 5',
    brand: 'Cannondale',
    fullName: 'Cannondale Trail 5',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹42,000',
    price_usd: '$506',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/cannondale-trail-5.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'cannondale-trail-6',
    name: 'Trail 6',
    brand: 'Cannondale',
    fullName: 'Cannondale Trail 6',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹35,000',
    price_usd: '$421',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/cannondale-trail-6.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'cannondale-trail-7',
    name: 'Trail 7',
    brand: 'Cannondale',
    fullName: 'Cannondale Trail 7',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹28,000',
    price_usd: '$337',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/cannondale-trail-7.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'cannondale-quick-3',
    name: 'Quick 3',
    brand: 'Cannondale',
    fullName: 'Cannondale Quick 3',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹48,000',
    price_usd: '$578',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/cannondale-quick-3.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'cannondale-quick-cx-4',
    name: 'Quick CX 4',
    brand: 'Cannondale',
    fullName: 'Cannondale Quick CX 4',
    category: 'Gravel',
    type: 'Gravel Bike',
    price_inr: '₹55,000',
    price_usd: '$662',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/cannondale-quick-cx-4.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'scott-aspect-940',
    name: 'Aspect 940',
    brand: 'Scott',
    fullName: 'Scott Aspect 940',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹32,000',
    price_usd: '$385',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/scott-aspect-940.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'scott-aspect-950',
    name: 'Aspect 950',
    brand: 'Scott',
    fullName: 'Scott Aspect 950',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹28,000',
    price_usd: '$337',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/scott-aspect-950.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'scott-scale-970',
    name: 'Scale 970',
    brand: 'Scott',
    fullName: 'Scott Scale 970',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹65,000',
    price_usd: '$783',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/scott-scale-970.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'scott-contessa-active',
    name: 'Contessa Active',
    brand: 'Scott',
    fullName: 'Scott Contessa Active',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹35,000',
    price_usd: '$421',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/scott-contessa-active.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'merida-big-nine-100',
    name: 'Big Nine 100',
    brand: 'Merida',
    fullName: 'Merida Big Nine 100',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹32,000',
    price_usd: '$385',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/merida-big-nine-100.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'merida-big-nine-200',
    name: 'Big Nine 200',
    brand: 'Merida',
    fullName: 'Merida Big Nine 200',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹42,000',
    price_usd: '$506',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/merida-big-nine-200.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'merida-big-seven-100',
    name: 'Big Seven 100',
    brand: 'Merida',
    fullName: 'Merida Big Seven 100',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹28,000',
    price_usd: '$337',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/merida-big-seven-100.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'merida-scultura-200',
    name: 'Scultura 200',
    brand: 'Merida',
    fullName: 'Merida Scultura 200',
    category: 'Road',
    type: 'Road Bike',
    price_inr: '₹65,000',
    price_usd: '$783',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/merida-scultura-200.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'merida-crossway-20',
    name: 'Crossway 20',
    brand: 'Merida',
    fullName: 'Merida Crossway 20',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹35,000',
    price_usd: '$421',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/merida-crossway-20.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'marin-fairfax-1',
    name: 'Fairfax 1',
    brand: 'Marin',
    fullName: 'Marin Fairfax 1',
    category: 'City',
    type: 'City Bike',
    price_inr: '₹38,000',
    price_usd: '$457',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/marin-fairfax-1.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'marin-fairfax-2',
    name: 'Fairfax 2',
    brand: 'Marin',
    fullName: 'Marin Fairfax 2',
    category: 'City',
    type: 'City Bike',
    price_inr: '₹48,000',
    price_usd: '$578',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/marin-fairfax-2.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'marin-bobcat-trail',
    name: 'Bobcat Trail',
    brand: 'Marin',
    fullName: 'Marin Bobcat Trail',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹42,000',
    price_usd: '$506',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/marin-bobcat-trail.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'marin-gestalt',
    name: 'Gestalt',
    brand: 'Marin',
    fullName: 'Marin Gestalt',
    category: 'Gravel',
    type: 'Gravel Bike',
    price_inr: '₹55,000',
    price_usd: '$662',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/marin-gestalt.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'marin-rift-zone',
    name: 'Rift Zone',
    brand: 'Marin',
    fullName: 'Marin Rift Zone',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹85,000',
    price_usd: '$1024',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/marin-rift-zone.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'marin-dsx',
    name: 'DSX',
    brand: 'Marin',
    fullName: 'Marin DSX',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹72,000',
    price_usd: '$867',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/marin-dsx.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'polygon-path-2',
    name: 'Path 2',
    brand: 'Polygon',
    fullName: 'Polygon Path 2',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹28,000',
    price_usd: '$337',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/polygon-path-2.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'polygon-strattos-s2',
    name: 'Strattos S2',
    brand: 'Polygon',
    fullName: 'Polygon Strattos S2',
    category: 'Road',
    type: 'Road Bike',
    price_inr: '₹45,000',
    price_usd: '$542',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/polygon-strattos-s2.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'polygon-cascade-3',
    name: 'Cascade 3',
    brand: 'Polygon',
    fullName: 'Polygon Cascade 3',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹32,000',
    price_usd: '$385',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/polygon-cascade-3.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'polygon-xtrada-6',
    name: 'Xtrada 6',
    brand: 'Polygon',
    fullName: 'Polygon Xtrada 6',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹55,000',
    price_usd: '$662',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/polygon-xtrada-6.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'polygon-heist-x2',
    name: 'Heist X2',
    brand: 'Polygon',
    fullName: 'Polygon Heist X2',
    category: 'Urban',
    type: 'Urban Bike',
    price_inr: '₹38,000',
    price_usd: '$457',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/polygon-heist-x2.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'btwin-rockrider-st100',
    name: 'Rockrider ST100',
    brand: 'Btwin',
    fullName: 'Btwin Rockrider ST100',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹8,999',
    price_usd: '$108',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/btwin-rockrider-st100.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'btwin-rockrider-st120',
    name: 'Rockrider ST120',
    brand: 'Btwin',
    fullName: 'Btwin Rockrider ST120',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹10,999',
    price_usd: '$132',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/btwin-rockrider-st120.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'btwin-rockrider-st520',
    name: 'Rockrider ST520',
    brand: 'Btwin',
    fullName: 'Btwin Rockrider ST520',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹18,999',
    price_usd: '$228',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/btwin-rockrider-st520.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'btwin-riverside-120',
    name: 'Riverside 120',
    brand: 'Btwin',
    fullName: 'Btwin Riverside 120',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹12,999',
    price_usd: '$156',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/btwin-riverside-120.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'btwin-riverside-500',
    name: 'Riverside 500',
    brand: 'Btwin',
    fullName: 'Btwin Riverside 500',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹22,999',
    price_usd: '$277',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/btwin-riverside-500.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'cradiac-gunner-pro',
    name: 'Gunner Pro',
    brand: 'Cradiac',
    fullName: 'Cradiac Gunner Pro',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹14,000',
    price_usd: '$168',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/cradiac-gunner-pro.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'cradiac-squad',
    name: 'Squad',
    brand: 'Cradiac',
    fullName: 'Cradiac Squad',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹11,000',
    price_usd: '$132',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/cradiac-squad.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'cradiac-alpha-pro',
    name: 'Alpha Pro',
    brand: 'Cradiac',
    fullName: 'Cradiac Alpha Pro',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹12,500',
    price_usd: '$150',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/cradiac-alpha-pro.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'leader-beast-26t',
    name: 'Beast 26T',
    brand: 'Leader',
    fullName: 'Leader Beast 26T',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹6,500',
    price_usd: '$78',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/leader-beast-26t.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'leader-scout',
    name: 'Scout',
    brand: 'Leader',
    fullName: 'Leader Scout',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹8,000',
    price_usd: '$96',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/leader-scout.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'java-fuoco',
    name: 'Fuoco',
    brand: 'Java',
    fullName: 'Java Fuoco',
    category: 'Road',
    type: 'Road Bike',
    price_inr: '₹55,000',
    price_usd: '$662',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/java-fuoco.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'omo-hybrid-700c',
    name: 'Hybrid 700C',
    brand: 'OMO',
    fullName: 'OMO Hybrid 700C',
    category: 'Hybrid',
    type: 'Hybrid Bike',
    price_inr: '₹32,000',
    price_usd: '$385',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/omo-hybrid-700c.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'kross-maximus',
    name: 'Maximus',
    brand: 'Kross',
    fullName: 'Kross Maximus',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹28,000',
    price_usd: '$337',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/kross-maximus.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'kross-xceed',
    name: 'Xceed',
    brand: 'Kross',
    fullName: 'Kross Xceed',
    category: 'MTB',
    type: 'MTB Bike',
    price_inr: '₹35,000',
    price_usd: '$421',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/kross-xceed.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
  {
    id: 'kross-viper',
    name: 'Viper',
    brand: 'Kross',
    fullName: 'Kross Viper',
    category: 'Road',
    type: 'Road Bike',
    price_inr: '₹42,000',
    price_usd: '$506',
    weight: '14.2kg',
    frame: 'Aluminum',
    fork: 'SR Suntour XCT',
    wheelSize: '27.5"',
    speeds: 21,
    brakes: 'Mechanical Disc',
    groupset: 'Shimano Tourney',
    skillLevel: 'beginner',
    terrain: ['trail', 'city'],
    image: '/images/kross-viper.jpg',
    tags: ['entry-level', 'trail', 'hardtail']
  },
];
